name: Build Hyper-bola-1 APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant Execute Permission for Gradle Wrapper
        run: chmod +x gradlew

      # --- DEBUG BUILD ---
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Hyper-bola-1-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      # --- RELEASE BUILD (Only runs if secrets exist) ---
      - name: Decode Keystore
        if:
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore

      - name: Build Signed Release APK
        if:
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/release.keystore
          STORE_PASSWORD: ${{ AIzaSyBq8D0sALJCygxEju82MlE0ekHeEAuB7hQ}}
          KEY_PASSWORD: ${{ AIzaSyBq8D0sALJCygxEju82MlE0ekHeEAuB7hQ }}
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        if: 
        uses: actions/upload-artifact@v4
        with:
          name: Hyper-bola-1-release-apk
          path: app/build/outputs/apk/release/*.apk
          
